version: "3"
services:
  sloe-frontend:
    build: .
    user: 1000:1000
    container_name: sloe-frontend
    networks:
      - traefik
    ports:
      - 8084:3000
    volumes:
      - ./build/standalone:/app
    restart: unless-stopped

networks:
  traefik:
    name: traefik
    external: true
