version: "3"
services:
  sloe-frontend:
    build: .
    container_name: sloe-frontend
    networks:
      - traefik
    ports:
      - 8084:3000

networks:
  traefik:
    name: traefik
    external: true
